image:
  registry: docker.io
  repository: bitnami/minio
  tag: 2024.9.17-debian-12-r0   # ✅ มีจริงแน่นอน

console:
  image:
    registry: docker.io
    repository: bitnami/minio-client
    tag: 2024.9.17-debian-12-r0   # ✅ มีจริงแน่นอน

mode: standalone

persistence:
  enabled: true
  size: 10Gi

auth:
  rootUser: minioadmin
  rootPassword: minioadmin123

defaultBuckets: "velero"

service:
  type: NodePort
